### ISSUE TITLE
Kernel size

### ISSUE THREAD

**Issue by CongWeilin** [MiguelMonteiro/permutohedral_lattice#13]
Thanks for the effort implementing the code, good to know it can support multi-batch. However, after reading the code, can I assume this bilateral filter is applied on a densely connected graph? Say, pixel (0,0) are jointly computed with all other pixels (i,j) except itself. Please clarify if I am wrong.

Regards,

**Comment by MiguelMonteiro** [comment]
That is correct.

However multiple examples in a batch are computing sequentially.
