### ISSUE TITLE
The purpose of the reverse in the blur stage

### ISSUE THREAD

**Issue by wang-ps** [MiguelMonteiro/permutohedral_lattice#14]
First of all, thank you so much for sharing your implementation.
Could you please explain why the parameter reverse is set to false in the bilateral filter and true in the back propagation stage?

**Comment by MiguelMonteiro** [comment]
This was something described in the original code and paper for the CRFasRNN gradients.
When I coded it I just followed their lead and didn't really understand why.
In time I have come to realise that this is not needed since blurring in reverse is virtually the same as regular blurring.

**Comment by wang-ps** [comment]
Thanks for your reply!
