### ISSUE TITLE
Pytorch?

### ISSUE THREAD

**Issue by jgsimard** [MiguelMonteiro/permutohedral_lattice#18]
Hi,
Just to know, will there be a PyTorch extension of this code?
Thanks

**Comment by MiguelMonteiro** [comment]
Hello,

I have switched over to pytorch myself. Unfortunately, I don't have time at the moment to pursue this project further. But it is in the plans to transfer it over to pytorch in the future (just don't know when).

Best,

Miguel

**Comment by jgsimard** [comment]
Thanks for the quick reply!
