### ISSUE TITLE
3D pointcloud

### ISSUE THREAD

**Issue by jgsimard** [MiguelMonteiro/permutohedral_lattice#19]
Hi,
I would like to know how could I use this code for 3D point cloud. 

From what I understand, I would need to have put SPATIAL_DIMS=3, but this would require me to have a 3d point everywhere. On the contrary, what I have is a list of 3D sparse points that do not fill the whole space and are no regularly spaced out. Each point has a 3D feature vector (RGB).

So basically, my question is : can i use your code if I have sparsity in the spatial dimensions?

Thanks

**Comment by MiguelMonteiro** [comment]
Hello,
I am not familiar with point clouds.
This C++ code applies a CRF on a fully connected graph, it is not required that it is an image.
That being said the way the graph is defined, the function that calculates the affinity between the nodes, is specific to images in the sense that it uses distance in space as well as the channel values.
This can be changed by changing the functions that computes this affinity `compute_kernel` to make the rest of the code applicable to the new type of graph.
I don't know how easy/hard this is for point clouds though.

Best Regards,

Miguel

**Comment by jgsimard** [comment]
Hi,
The point cloud is list of N different 3D points with 1D or 3D features. So I have a matrix of dimension Nx4 or Nx6. I want to do the CRF on a fully connected graph, but I struggle to see how to change your code.
Thanks

**Comment by MiguelMonteiro** [comment]
The 'compute_kernel' function does nothing more than converting an image to an array of sequential vectors `[x_1, y_1, r_1, g_1, b_1, x_2, y_2, r_2, g_2, b_2 ...]` so if you already have your data in this format you can just bypass this function and feed the data straight into the CRF.

Best,

Miguel
