### ISSUE TITLE
About Speed acceleration

### ISSUE THREAD

**Issue by hrtan** [MiguelMonteiro/permutohedral_lattice#20]
Your work is very valuable. I have a stupid question that How many times faster is the cuda version compared to the cpu version? Because I have no Gpu now....

**Comment by MiguelMonteiro** [comment]
Hello,

Not a stupid question at all.
I can't remember the exact speed up but I can say when I was working on
this the speed up would be something like 50-100x on a gpu.

Best,

Miguel
