### ISSUE TITLE
Possibly incorrect number of blocks/blockSize?

### ISSUE THREAD

**Issue by achirkin** [MiguelMonteiro/permutohedral_lattice#23]
I've been working on some adaptation of your code and noticed something inconsistent:

https://github.com/MiguelMonteiro/permutohedral_lattice/blob/fe04895526dd39e5ea01c35194b7199c04f9e680/src/PermutohedralLatticeGPU.cuh#L476

Shouldn't here be `blocks.y = 1;`? `blockSize.y` seems to be equal to one already. In my understanding, the result is that the same computation is run `pd + 1` times. Though it's not entirely clear if this is harmful.

**Comment by MiguelMonteiro** [comment]
Sorry it's been awhile I don't know how to answer your question.
