### ISSUE TITLE
About kernel normalization

### ISSUE THREAD

**Issue by netw0rkf10w** [MiguelMonteiro/permutohedral_lattice#24]
Hi @MiguelMonteiro,

Thanks for sharing your code!

I know you no longer work on this project, but I would like to ask just a quick question that I hope wouldn't take much of your time.

In Krähenbühl's [paper](http://proceedings.mlr.press/v28/kraehenbuehl13.pdf), first paragraph of Section 5, he mentioned two types of normalization (symmetric and asymmetric) that greatly increase the accuracy of the approximate filtering. Do you remember doing anything like that in your code?

Thank you in advance for your response!

**Comment by MiguelMonteiro** [comment]
Sorry it's been awhile can't remember what I did.
