### ISSUE TITLE
Build.sh runs successfully, but no ./build_dir is created

### ISSUE THREAD

**Issue by GMNetto** [MiguelMonteiro/permutohedral_lattice#26]
Hi,

I get to run build.sh after changing the file to use the default g++ and nvcc I have installed. However, after a point I get the following message 
```
[ 50%] Building CUDA object CMakeFiles/lattice_filter.dir/src/LatticeFilterKernel.cu.o                                                                                

/home/gustavo/.local/lib/python3.6/site-packages/tensorflow/include/absl/strings/string_view.h(495): warning: expression has no effect /home/gustavo/.local/lib/python3.6/site-packages/tensorflow/include/unsupported/Eigen/CXX11/../../../Eige/src/Core/MathFunctions.h(1288): warning: calling a constexpr __host__ function("real") from a __host__ __device__ function("abs") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
```
After this, I tried to update the CMakeLists.txt file with the flag
`set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} --expt-relaxed-constexpr")`

However, it did not fix. Would you have some idea about how to solve this?

Thanks

**Comment by MiguelMonteiro** [comment]
Hello,

The `build_dir` is automatically deleted by build.sh since you only need the `lattice_filter.so` file in the end.
The three last lines of the build.sh script are:

```
cp lattice_filter.so ../
cd ..
rm -r build_dir
```

The warning happens all the the time but it does not have an impact on the build.
