### ISSUE TITLE
Changes for CPU compilation

### ISSUE THREAD

**Issue by manishh** [MiguelMonteiro/permutohedral_lattice#4]
Could you please list down what all changes would be required in `CMakeLists.txt` for CPU-only version of this code?

**Comment by MiguelMonteiro** [comment]
I have been meaning to implement a flag in `CMakeLists.txt` that compiles only the CPU version. The changes are not big but I would have to look into it. I am currently on vacation and will look at it when I get back. If you manage to figure it out for yourself feel free to submit a pull request.

Best Regards,

Miguel

**Comment by asafmanor** [comment]
Hi Miguel! any update on that?

**Comment by MiguelMonteiro** [comment]
Sorry I have no time to focus on this project at the moment
