### ISSUE TITLE
Could you share this project's environment ?

### ISSUE THREAD

**Issue by lixingang** [MiguelMonteiro/permutohedral_lattice#8]
I successfully build this project, but encounter such problem: 
`
tensorflow.python.framework.errors_impl.NotFoundError: /home/data/lixg/Mig_CRF/permutohedral_lattice/lattice_filter.so: undefined symbol: _ZN10tensorflow7strings6StrCatERKNS0_8AlphaNumE
`
So, I guess it's concerned about the environment.

**Comment by MiguelMonteiro** [comment]
That seems like a compilation error, the compilation scripts are made for linux and mac, are you running on windows?
